language: node_js
node_js:
  - "8"
  - "10"
  - "node"
sudo: false
install: yarn install
script:
  - yarn run lint
  - yarn test
notifications:
  email:
    on_success: change
    on_failure: change

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage